#when multi service will be used such a service yaml can be used api service
apiVersion: v1
kind: Service
metadata:
  name: address-api-service
  labels:
    name: address-api-service
    app: address-api
spec:
  type: ClusterIP
  ports:
    - port: 4001
      targetPort: 4001
  selector:
    name: address-api-pod
    app: address-api        