apiVersion: v1
kind: Service
metadata:
  name: address-api-service
  labels:
    name: address-api-service
    app: address-api
spec:
  type: LoadBalancer
  ports:
    - port: 4001
      targetPort: 4001       
  selector:
    name: address-api-pod
    app: address-api 
